### ISSUE TITLE
Imported Files Are Blank

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-metal#18]
I have the following zip file structure:
```
[root@management1 [Flight Management] unzip]# unzip /root/underware-2019-06-03-16-19-53.zip
Archive:  /root/underware-2019-06-03-16-19-53.zip
  inflating: kickstart/manifest.yaml
  inflating: kickstart/node/node07/core/networking/hosts.sh
  inflating: kickstart/node/node07/core/networking/gateway.sh
  inflating: kickstart/node/node07/core/networking/networking.sh
  inflating: kickstart/node/node07/core/networking/main.sh
  inflating: kickstart/node/node07/core/base/main.sh
  inflating: kickstart/node/node07/core/main.sh
  inflating: kickstart/node/node07/platform/node07.ks
  inflating: kickstart/node/node07/platform/pxelinux.cfg/pxe_bios
  inflating: kickstart/node/node07/platform/pxelinux.cfg/pxe_uefi
  inflating: kickstart/node/node03/core/networking/hosts.sh
  inflating: kickstart/node/node03/core/networking/gateway.sh
  inflating: kickstart/node/node03/core/networking/networking.sh
  inflating: kickstart/node/node03/core/networking/main.sh
  inflating: kickstart/node/node03/core/base/main.sh
  inflating: kickstart/node/node03/core/main.sh
  inflating: kickstart/node/node03/platform/node03.ks
  inflating: kickstart/node/node03/platform/pxelinux.cfg/pxe_bios
  inflating: kickstart/node/node03/platform/pxelinux.cfg/pxe_uefi
  inflating: kickstart/node/node04/core/networking/hosts.sh
  inflating: kickstart/node/node04/core/networking/gateway.sh
  inflating: kickstart/node/node04/core/networking/networking.sh
  inflating: kickstart/node/node04/core/networking/main.sh
  inflating: kickstart/node/node04/core/base/main.sh
  inflating: kickstart/node/node04/core/main.sh
  inflating: kickstart/node/node04/platform/pxelinux.cfg/pxe_bios
  inflating: kickstart/node/node04/platform/pxelinux.cfg/pxe_uefi
  inflating: kickstart/node/node04/platform/node04.ks
  inflating: kickstart/node/node08/core/networking/hosts.sh
  inflating: kickstart/node/node08/core/networking/gateway.sh
  inflating: kickstart/node/node08/core/networking/networking.sh
  inflating: kickstart/node/node08/core/networking/main.sh
  inflating: kickstart/node/node08/core/base/main.sh
  inflating: kickstart/node/node08/core/main.sh
  inflating: kickstart/node/node08/platform/pxelinux.cfg/pxe_bios
  inflating: kickstart/node/node08/platform/pxelinux.cfg/pxe_uefi
  inflating: kickstart/node/node08/platform/node08.ks
  inflating: kickstart/node/node01/core/networking/hosts.sh
  inflating: kickstart/node/node01/core/networking/gateway.sh
  inflating: kickstart/node/node01/core/networking/networking.sh
  inflating: kickstart/node/node01/core/networking/main.sh
  inflating: kickstart/node/node01/core/base/main.sh
  inflating: kickstart/node/node01/core/main.sh
  inflating: kickstart/node/node01/platform/node01.ks
  inflating: kickstart/node/node01/platform/pxelinux.cfg/pxe_bios
  inflating: kickstart/node/node01/platform/pxelinux.cfg/pxe_uefi
  inflating: kickstart/node/node06/core/networking/hosts.sh
  inflating: kickstart/node/node06/core/networking/gateway.sh
  inflating: kickstart/node/node06/core/networking/networking.sh
  inflating: kickstart/node/node06/core/networking/main.sh
  inflating: kickstart/node/node06/core/base/main.sh
  inflating: kickstart/node/node06/core/main.sh
  inflating: kickstart/node/node06/platform/pxelinux.cfg/pxe_bios
  inflating: kickstart/node/node06/platform/pxelinux.cfg/pxe_uefi
  inflating: kickstart/node/node06/platform/node06.ks
  inflating: kickstart/node/node10/core/networking/hosts.sh
  inflating: kickstart/node/node10/core/networking/gateway.sh
  inflating: kickstart/node/node10/core/networking/networking.sh
  inflating: kickstart/node/node10/core/networking/main.sh
  inflating: kickstart/node/node10/core/base/main.sh
  inflating: kickstart/node/node10/core/main.sh
  inflating: kickstart/node/node10/platform/node10.ks
  inflating: kickstart/node/node10/platform/pxelinux.cfg/pxe_bios
  inflating: kickstart/node/node10/platform/pxelinux.cfg/pxe_uefi
  inflating: kickstart/node/node02/core/networking/hosts.sh
  inflating: kickstart/node/node02/core/networking/gateway.sh
  inflating: kickstart/node/node02/core/networking/networking.sh
  inflating: kickstart/node/node02/core/networking/main.sh
  inflating: kickstart/node/node02/core/base/main.sh
  inflating: kickstart/node/node02/core/main.sh
  inflating: kickstart/node/node02/platform/pxelinux.cfg/pxe_bios
  inflating: kickstart/node/node02/platform/pxelinux.cfg/pxe_uefi
  inflating: kickstart/node/node02/platform/node02.ks
  inflating: kickstart/node/node05/core/networking/hosts.sh
  inflating: kickstart/node/node05/core/networking/gateway.sh
  inflating: kickstart/node/node05/core/networking/networking.sh
  inflating: kickstart/node/node05/core/networking/main.sh
  inflating: kickstart/node/node05/core/base/main.sh
  inflating: kickstart/node/node05/core/main.sh
  inflating: kickstart/node/node05/platform/node05.ks
  inflating: kickstart/node/node05/platform/pxelinux.cfg/pxe_bios
  inflating: kickstart/node/node05/platform/pxelinux.cfg/pxe_uefi
  inflating: kickstart/node/node09/core/networking/hosts.sh
  inflating: kickstart/node/node09/core/networking/gateway.sh
  inflating: kickstart/node/node09/core/networking/networking.sh
  inflating: kickstart/node/node09/core/networking/main.sh
  inflating: kickstart/node/node09/core/base/main.sh
  inflating: kickstart/node/node09/core/main.sh
  inflating: kickstart/node/node09/platform/pxelinux.cfg/pxe_bios
  inflating: kickstart/node/node09/platform/pxelinux.cfg/pxe_uefi
  inflating: kickstart/node/node09/platform/node09.ks
  inflating: kickstart/node/gateway1/core/networking/hosts.sh
  inflating: kickstart/node/gateway1/core/networking/gateway.sh
  inflating: kickstart/node/gateway1/core/networking/networking.sh
  inflating: kickstart/node/gateway1/core/networking/main.sh
  inflating: kickstart/node/gateway1/core/base/main.sh
  inflating: kickstart/node/gateway1/core/main.sh
  inflating: kickstart/node/gateway1/platform/gateway1.ks
  inflating: kickstart/node/gateway1/platform/pxelinux.cfg/pxe_bios
  inflating: kickstart/node/gateway1/platform/pxelinux.cfg/pxe_uefi
  inflating: kickstart/domain/platform/manifest.yaml
```

The kickstart definitely has content
```
[root@management1 [Flight Management] unzip]# cat kickstart/node/gateway1/platform/gateway1.ks 
#!/bin/bash
#(c)2017 Alces Software Ltd. HPC Consulting Build Suite
# vim: set filetype=kickstart :

#MISC
text
reboot
skipx
install
...
```

With the following manifest
```
[root@management1 [Flight Management] unzip]# cat kickstart/manifest.yaml
gateway1:
  kickstart_file: kickstart/node/gateway1/platform/gateway1.ks
  pxelinux_file: kickstart/node/gateway1/platform/pxelinux.cfg/pxe_bios
node01:
  kickstart_file: kickstart/node/node01/platform/node01.ks
  pxelinux_file: kickstart/node/node01/platform/pxelinux.cfg/pxe_bios
node02:
  kickstart_file: kickstart/node/node02/platform/node02.ks
  pxelinux_file: kickstart/node/node02/platform/pxelinux.cfg/pxe_bios
node03:
  kickstart_file: kickstart/node/node03/platform/node03.ks
  pxelinux_file: kickstart/node/node03/platform/pxelinux.cfg/pxe_bios
node04:
  kickstart_file: kickstart/node/node04/platform/node04.ks
  pxelinux_file: kickstart/node/node04/platform/pxelinux.cfg/pxe_bios
node05:
  kickstart_file: kickstart/node/node05/platform/node05.ks
  pxelinux_file: kickstart/node/node05/platform/pxelinux.cfg/pxe_bios
node06:
  kickstart_file: kickstart/node/node06/platform/node06.ks
  pxelinux_file: kickstart/node/node06/platform/pxelinux.cfg/pxe_bios
node07:
  kickstart_file: kickstart/node/node07/platform/node07.ks
  pxelinux_file: kickstart/node/node07/platform/pxelinux.cfg/pxe_bios
node08:
  kickstart_file: kickstart/node/node08/platform/node08.ks
  pxelinux_file: kickstart/node/node08/platform/pxelinux.cfg/pxe_bios
node09:
  kickstart_file: kickstart/node/node09/platform/node09.ks
  pxelinux_file: kickstart/node/node09/platform/pxelinux.cfg/pxe_bios
node10:
  kickstart_file: kickstart/node/node10/platform/node10.ks
  pxelinux_file: kickstart/node/node10/platform/pxelinux.cfg/pxe_bios
```

And when I do an import
```
[root@management1 [Flight Management] dhcp]# flight metal import /root/underware-2019-06-03-16-19-53.zip
Imported: gateway1
Imported: node01
Imported: node02
Imported: node03
Imported: node04
Imported: node05
Imported: node06
Imported: node07
Imported: node08
Imported: node09
Imported: node10
```

However the kickstart is blank?
```
[root@management1 [Flight Management] dhcp]# cat /opt/flight/opt/metal/var/clusters/default/var/nodes/gateway1/var/templates/gateway1.ks
[root@management1 [Flight Management] dhcp]#
```

This is the same for pxe files!!
